add_newline = false
format = '''[\[](bold red)$username@$hostname $directory[\]](bold red) $git_branch$git_status
$character'''

[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"

[directory]
truncate_to_repo = true
truncation_length = 8
truncation_symbol = "…/"
home_symbol = "~"
style = "purple"
format = "[$path]($style)$read_only"

[hostname]
ssh_only = false
format =  "[$hostname](bold cyan)"
disabled = false

[username]
style_user = "bold yellow"
style_root = "bold green"
format = "[$user]($style)"
disabled = false
show_always = true

[conda]
disabled = false
